Repository pineapplemachine/jsdoom, pull requests merged in 2018-11, with the labels that each got.

#5 Fix tall patch rendering
  src/lumps/doom/picture.ts
Labels: type: bug

#6 Sophie/minor cleanup
  src/lumps/doom/colormap.ts
  src/lumps/doom/colormapNames.ts
  src/lumps/doom/colors.ts
  src/lumps/doom/index.ts
  src/lumps/doom/playpal.ts
  web/inspector.css
  web/lumpTypeView.ts
Labels: type: code quality, type: polish

#4 Add code of conduct and style guide
  conduct.md
  readme.md
  style.md
Labels: type: documentation
